project_id = "eebyqnqnmujguosbuxxx"

[functions.publish-scheduled-news]
verify_jwt = false

[functions.send-newsletter]
verify_jwt = false

[functions.unsubscribe-newsletter]
verify_jwt = false

[functions.confirm-newsletter-subscription]
verify_jwt = false

[functions.verify-newsletter-subscription]
verify_jwt = false
